# Generated by Django 4.0 on 2024-11-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_deployment',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.catagory'),
        ),
    ]
