# Generated by Django 4.0 on 2024-11-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_school_deployment_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='discriptionsTwo',
            field=models.TextField(null=True),
        ),
    ]
