# Generated by Django 4.0 on 2024-11-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_catagory_discriptionstwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='discriptionsTwo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
