# Generated by Django 4.0 on 2024-11-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_alter_catagory_discriptionstwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_deployment',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='school_deployment',
            name='image',
        ),
    ]
